# NumPy I

*Autor: José Chávez*

## ¿Como sumar dos listas?

Tenemos dos listas "a" y "b", ambas con la misma cantidad de elementos y con todos sus elementos numéricos.

In [ ]:
a = [1,3,4,5]
a

In [ ]:
b = [1,7,3,5]
b

In [ ]:
c = []   # Lista vacia
for i, j in zip(a,b):  # zip para concatenar la lista 'a' y 'b'
  c.append(i+j)        # '.append' agregar un nuevo elemento a la lista 'c'

print(c)

La función $\texttt{zip()}$ retorna una tupla de iterables. Es decir en cada iteración selecciona un elemento de "a" y un elemento de "b" y los junta.

Podemos optimizar esta operación utilizando Numpy.

In [ ]:
import numpy as np

# Un Array en Numpy

Una array tiene la particularidad de que todos sus elementos son del mismo tipo ($\texttt{int,float,bool,}$etc). En Python, la formal en la cual podemos crear una array de Numpy es la siguiente:

$$\texttt{np.array(x)}$$

donde $\texttt{x}$ es una secuencia de elementos, como por ejemplo una Lista.

## Creando un array con Numpy

In [ ]:
a1d = np.array([1,2,3])
a1d

array([1, 2, 3])

In [ ]:
a1d.shape

(3,)

El método $\texttt{shape}$ nos permite calcular el tamaño del array.

Podemos crear un array con una lista de listas (listas anidadas).

In [ ]:
a2d = np.array([[1,2],[3,4]])
a2d

array([[1, 2],
       [3, 4]])

In [ ]:
a2d.shape

(2, 2)

In [ ]:
a2d.ndim

2

In [ ]:
a3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a3d.shape

(2, 2, 2)

In [ ]:
a3d.ndim

3

El método $\texttt{ndim}$ nos permite calcular cuantas dimensiones posee el actual array. En Numpy, podemos crear arrays de una o más dimensiones:
* $\texttt{a1d}$: array de una dimensión.
* $\texttt{a2d}$: array de dos dimensión.
* $\texttt{a3d}$: array de tres dimensión.

Por último, podemos cambiar las dimensiones de un array utilizando el argumento $\texttt{ndim}$

In [ ]:
a1d

array([1, 2, 3])

In [ ]:
print(a1d.ndim)

1


In [ ]:
# ndmin
m = np.array(a1d, ndmin=2)

print(m)

[[1 2 3]]


In [ ]:
print(m.ndim)

2


## Recordemos que todos los elementos de un array son del mismo tipo

In [ ]:
m = np.array([1, 2, 4])

print(m.dtype)

int64


In [ ]:
m = np.array([1, 2, 4.5])
print(m.dtype)

float64


In [ ]:
m

array([1. , 2. , 4.5])

En este último caso "4.5" es de tipo $\texttt{float}$, por lo cual el tipo de dato para todos los elementos del array será $\texttt{float}$.

## Copiar el contenido de un array a otro

Si queremos crear un nuevo array pero con los mismo elementos de otro, tenemos que utilizar el método $\texttt{copy}$.

In [ ]:
a = np.array([1,3,5]) # a=[1,3,5] -> a=[10,3,5]

In [ ]:
b = a
c = np.copy(a)

In [ ]:
a[0] = 10

In [ ]:
print(f"a = {a}")
print(f"b = {b}")
print(f"c = {c}")

a = [10  3  5]
b = [10  3  5]
c = [1 3 5]


# Listas vs NumPy

¿Porque utilizar Numpy si puedo utilizar Listas?

Esta es la pregunta que responderemos a continuación. Para lo cual validaremos los resultados mostrar la memoria que ocupa un Array de Numpy y que tan rápidas son las operaciones de un Array comparadas con las de una Lista.


In [ ]:
import time

## Memoria

In [ ]:
import sys

In [ ]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
len(L)

10

In [ ]:
sys.getsizeof(1)

28

In [ ]:
print("{:d} bytes en una lista de 10 enteros".format(sys.getsizeof(1)*len(L)))

280 bytes en una lista de 10 enteros


In [ ]:
A = np.array(range(10))
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
A.size

10

In [ ]:
A.itemsize

8

In [ ]:
print("{:d} bytes en una array de 10 enteros".format(A.itemsize * A.size))

80 bytes en una array de 10 enteros


## Tiempo computacional

### Listas

In [ ]:
N = 1000000

In [ ]:
a = list(range(N)) # a=[0,1,2,...,999999]
b = list(range(N)) # b=[0,1,2,...,999999]

In [ ]:
type(a)

list

In [ ]:
type(b)

list

In [ ]:
start = time.time()

c = []
for i in range(len(a)):
  c.append(a[i] + b[i])

end = time.time()

print("tiempo: {:.2f}s".format(end-start))

tiempo: 0.27s


In [ ]:
time.time()

### Numpy

In [ ]:
a = np.array(range(N))
b = np.array(range(N))

In [ ]:
start = time.time()

c = a + b

end = time.time()

print("tiempo: {:.6f}s".format(end-start))

tiempo: 0.005911s


In [ ]:
a.dtype

# Generación de arrays predeterminados

En Numpy existen arrays que ya tienen una configuración definidad, donde unicamente tenemos que indicar el tamaño y las dimensiones.

## $\texttt{np.zeros(shape, dtype=float)}$

In [ ]:
x = np.zeros((5,8))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# ChatGPT (Tokenization)
# paso1 -> [0,0,0,0,0,0,0,0]
# INSTR -> Que dia es hoy?
# paso2 -> [57,999,91,1000,32]

# paso3 -> [57,999,91,1000,32,0,0,0] # este vector pasa como entrada al modelo


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x = np.zeros((2,3,2))
print(x)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


Crear una matriz de ceros del mismo tamaño de otra matriz

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
w, h = a.shape
print(w,h)

2 2


In [ ]:
x = np.zeros((w,h))
x

array([[0., 0.],
       [0., 0.]])

In [ ]:
z = np.zeros_like(a)
print(z, z.shape)

[[0 0]
 [0 0]] (2, 2)


## $\texttt{np.ones(shape, dtype=float)}$

In [ ]:
y = np.ones((4,8))
print(y)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
z = np.ones_like(a)
print(z)

[[1 1]
 [1 1]]


## $\texttt{np.full(shape, fill_value, dtype=None)}$

In [ ]:
u = np.full((4,4), 0.15)

print(u)

[[0.15 0.15 0.15 0.15]
 [0.15 0.15 0.15 0.15]
 [0.15 0.15 0.15 0.15]
 [0.15 0.15 0.15 0.15]]


## $\texttt{np.identity(n, dtype=None)}$

In [ ]:
I = np.identity(2)
I

array([[1., 0.],
       [0., 1.]])

In [ ]:
A = np.array([[1,3],[2,4]])
A

array([[1, 3],
       [2, 4]])

In [ ]:
A * I  # A * I -> A

array([[1., 0.],
       [0., 4.]])

In [ ]:
x = A @ I # Multiplicación de matrices
x

array([[1., 3.],
       [2., 4.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
np.eye(3,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

Matriz triangula inferior (Normalizing Flows)

In [ ]:
np.tril((3,3)) # lower (inferior)

array([[3, 0],
       [3, 3]])

Matriz triangular superior

In [ ]:
x = np.ones((7,7))
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
h = np.triu(x,k=0) # upper (superior)
h

array([[1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
h[0,0] = 3
h

In [ ]:
m = np.full((2,2,2),2)
m

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [ ]:
m[1,0,1]

# Inicialización

Una Red Neuronal esta compuesta por varias neuronas artificiales las cuales contienen **parámetros** que necesitan ser ajustados. Estos parámetros se ajustan durante el proceso de **aprendizaje**, el cual toma un tiempo. Cuando un Red Neuronal ajusta adecuadamente sus parámetros, decimos que ha "aprendido correctamente" su tarea. Sin embargo, podría darse el caso que el modelo "nunca llegue a aprender". Una herramienta importante para ayudar a que el modelo aprenda de manera correcta es la Inicialización.

El proceso de Initialización es de gran importancia dentro de los modelos de *Deep Learning*. La inicialización hace referencia a los valores iniciales de los parámetros. Una buena inicialización de los parámetros puede ayudar en el proceso de **convergencia** de una **Red Neuronal**.

El Deep Learning, existen varios métodos de Inicialización. No obstante, un estantar es utilizar una inicialización aleatoria. En este caso, se escoge de manera aleatoria muestras de alguna distribución conocida, principalmente la Gausiana y la Uniforme. A continuación se menciona alguna de las importantes configuraciones:

<figure>
<img src='https://drive.google.com/uc?id=1QQOQWcZRZ29Wkh8fl8R32UjCXoeb5J_A' width="600"/>
<figcaption>Image Caption</figcaption>
</figure>

### Distribución Normal: $\texttt{np.random.randn(d0, d1, ..., dn)}$

$w\sim\mathcal{N}(0,1)$

* $\mu=0$ y $\sigma^2=1$

In [ ]:
w = np.random.randn(3,3)
w

array([[-0.74034087, -1.37943963, -0.40449533],
       [ 0.13564175,  2.0674092 ,  1.33396119],
       [ 1.54146269, -0.13701952,  2.32365093]])

$\mu=3\\\sigma=1\\w\sim\mathcal{N}(\mu,\sigma^2)$

In [ ]:
w = np.random.randn(3,3) + 6 # media = 6
w

array([[ 7.35706232,  9.74040525, 10.27220065],
       [-0.50790904, 10.06166034,  2.33666045],
       [ 5.71603501, 10.98574682,  9.26414584]])

![](https://drive.google.com/uc?export=view&id=18qX6u3dyBwiwimya5k5umYJVzyP1LebH)

### Distrución Uniforme: $\texttt{np.random.uniform(low=0.0, high=1.0, size=None)}$

$u\sim\mathcal{U}(0,1)$

In [ ]:
np.random.uniform(size=(3,3)) # Los valores aleatorios están entre 0 y 1

array([[0.74514646, 0.4283973 , 0.11666675],
       [0.64041048, 0.08145948, 0.87110746],
       [0.05763213, 0.02504454, 0.55496768]])

Si quiero que los valores esten entre -5 y 5

In [ ]:
u = np.random.uniform(size=(3,3)) * 100
u

array([[48.69960919, 29.85824649, 42.43868814],
       [42.30417676, 47.63879785, 86.18047313],
       [37.26709868, 38.94407252, 38.68426983]])

### Distrución Uniforme: $\texttt{np.random.randint(low, high=None, size=None, dtype=int)}$

In [ ]:
x = np.random.randint(0,5,10) # randint(inicio, fin, cantidad) -> 0,1,2,3,...,fin-1
x

array([1, 2, 3, 2, 3, 1, 4, 2, 0, 4])

In [ ]:
np.random.randint(0,5,(2,3))

array([[3, 3, 4],
       [4, 1, 4]])

# Ejercicios:



## Ejercicio 1

Crear la matriz $X\in\mathbb{R}^{m\times m}$ con números aleatorios entre $-1$ y $1$ (decimales). Luego calcular $X^2 +2X + I$, donde $I$ es la matriz identidad. Note que $$X^2=XX$$Para el ejercicio utilice $m=6$.


In [ ]:
x = np.random.uniform(low=-1,high=1,size=(6,6))

print(x)

[[-0.49805226  0.50615894  0.13437785 -0.78958192 -0.33492415 -0.84969707]
 [ 0.42387105 -0.20249839 -0.35824235  0.70545798 -0.35970003  0.27246308]
 [ 0.87682785 -0.95637505  0.3255846   0.44806717 -0.1784518   0.25964764]
 [-0.61756158  0.28933373 -0.36625613  0.44421233 -0.55321662  0.94469261]
 [ 0.15601612  0.28128901 -0.10417318 -0.15040254  0.75821588  0.90874383]
 [-0.85815907 -0.44786559  0.97367494  0.62662142 -0.24846101  0.11048548]]


In [ ]:
y = x @ x + 2 * x + np.identity(6)

In [ ]:
print(y)

[[ 1.74886104  0.5870992  -0.43899712 -1.60143358 -0.31510231 -2.24755173]
 [-0.48891732  1.17407527 -0.65923726  1.31106842 -1.45529485  0.40624302]
 [ 0.66968215 -1.62349526  2.32490977  0.06358563 -0.81236294 -0.11197632]
 [-2.29738431  0.1075883  -0.22363945  3.28853994 -1.83823377  2.41914743]
 [-0.30645364  0.4469812   0.53885312  0.11635848  2.8138975   2.38185658]
 [-1.14555738 -2.10867171  2.21344629  2.43610584 -0.78465639  2.45931603]]


## Ejercicio 2

Crear la matriz $X\in\mathbb{R}^{m\times n}$ con números aleatorios de una distribución Normal con $\mu=0$ y $\sigma=1$ y calcule $$X^{T}X.$$ Note que $X^T$ es la transpuesta de la matriz $X$ y puede ser calculada con Numpy utilizando

$$\texttt{X_transpuesta = X.T}$$

Siendo $\texttt{X}$ la matriz original y $\texttt{X_transpuesta}$ la matriz transpuesta. Para el ejercicio utilice $m=5,n=4$.


In [ ]:
np.random.seed(7)

In [ ]:
x = np.random.randn(5,4) # sigma(dev.standar ) = 1
print(x)

[[-0.77805382  1.28661516 -1.77479946  1.14654092]
 [ 1.81950322 -1.92167682 -0.62356748 -0.63795515]
 [-1.60961401  0.8856413  -0.15906597  1.10208293]
 [ 1.06480205  0.37415834 -0.12565091  1.04608618]
 [ 1.29919851 -0.1813079   0.14771957  1.55146913]]


In [ ]:
np.random.randn(5,5) * 0.01 # sigma = 0.01

array([[-0.00728633, -0.00135044,  0.00808486, -0.00858391,  0.00155951],
       [ 0.01238048, -0.0087043 ,  0.01114713, -0.00936809,  0.00900349],
       [-0.00398326,  0.01382823,  0.01704135,  0.01752628, -0.00706613],
       [-0.00976604,  0.00113922, -0.01214244, -0.00465111,  0.02063345],
       [ 0.02285521, -0.01856034, -0.00055669,  0.00572452,  0.00596562]])

In [ ]:
print(x.shape)

(5, 4)


In [ ]:
x_t = x.T
print(x_t)

[[-0.77805382  1.81950322 -1.60961401  1.06480205  1.29919851]
 [ 1.28661516 -1.92167682  0.8856413   0.37415834 -0.1813079 ]
 [-1.77479946 -0.62356748 -0.15906597 -0.12565091  0.14771957]
 [ 1.14654092 -0.63795515  1.10208293  1.04608618  1.55146913]]


In [ ]:
print(x_t.shape)

(4, 5)


In [ ]:
y = x_t @ x   #  (4 x 5) (5 x 4) -> (4 x 4)

In [ ]:
# M1 : (m x n) y M2 : (p x q)
# Para multiplicar M1 M2 se debe cumplir que...

In [ ]:
print(y)

[[ 9.32853717 -5.76024403  0.56046498 -0.69721903]
 [-5.76024403  6.30544789 -1.29986017  3.78725896]
 [ 0.56046498 -1.29986017  3.60166073 -1.71463534]
 [-0.69721903  3.78725896 -1.71463534  6.43748237]]


In [ ]:
print(y.shape)

(4, 4)
